<?php 
session_start();
header('Content-Type: text/html; charset=UTF-8');
require_once("mysql.php"); 
?><!DOCTYPE html><html lang="vi"><head>    <meta charset="utf-8">    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">	<meta name="description" content="Phần mềm Themis online" />	<meta name="author" content="KT24H" />	<meta name="keyword" content="Phần mềm Themis online" />    <title><?php echo $TIEUDE;?></title>
	<meta property="og:title" content="<?php echo $TIEUDE;?>" />
	<meta property="og:image" content="img/opengraph.jpg" />
	<link rel="icon" type="image/png" href="img/64.png">    <!-- Bootstrap Core CSS -->    <link href="css/bootstrap.min.css" rel="stylesheet">    <!-- Custom CSS -->    <link href="css/sb-admin.css" rel="stylesheet">    <!-- Morris Charts CSS -->    <link href="css/plugins/morris.css" rel="stylesheet">    <!-- Custom Fonts -->    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->    <!--[if lt IE 9]>        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>    <![endif]--></head><body>    <div id="wrapper">        <!-- Navigation -->        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">            <!-- Brand and toggle get grouped for better mobile display -->            <div class="navbar-header">                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">                    <span class="sr-only">Toggle navigation</span>                    <span class="icon-bar"></span>                    <span class="icon-bar"></span>                    <span class="icon-bar"></span>                </button>             <!--   <a class="navbar-brand" href="index.php">SB Admin</a> -->				<a  href="./"><img src="img/logo.png" height="45"/></a>            </div>            <!-- Top Menu Items -->            <ul class="nav navbar-right top-nav">                                <li class="dropdown">                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?php	if (!isset($_SESSION['user_id']) || !$_SESSION['user_id'] )//fix  Undefined index					{						echo " Đăng Nhập "; 						echo '<b class="caret"></b></a><ul class="dropdown-menu">';										print <<<EOF<form action="login.php?act=do" method="post">Tên truy nhập: <input type="text" name="username" value="">Mật khẩu: <input type="password" name="password" value=""><input type="submit" name="submit" value="Đăng nhập"></form>EOF;															}															else{	$user_id = intval($_SESSION['user_id']);	$sql_query = "SELECT * FROM members WHERE id='{$user_id}'"; 	$member1 = $conn->query($sql_query); 
	$member = $member1->fetch_assoc();
	
		echo "Xin chào: {$member['Name']} ";	echo '<b class="caret"></b></a><ul class="dropdown-menu">';		echo "<li><a href='suathongtin.php'>Sửa tài khoản</a></li>";	echo "<li><a href='submit.php'>Nộp bài</a></li>";	echo "<li><a href='./?CBHT=thoat'>Thoát ra</a></li>";}																									?>					 </ul>                </li>            </ul>		   <?php include_once("menu.php"); ?>		               <!-- /.navbar-collapse -->        </nav>        <div id="page-wrapper">            <div class="container-fluid">                <!-- Page Heading -->                <div class="row">                    <div class="col-lg-12">                        <h1 class="page-header">                            Themis Web V2.1                        </h1>                        <ol class="breadcrumb">                            <li class="active">                                <i class="fa fa-dashboard"></i> <?php echo $TIEUDE;?>                            </li>                        </ol>                    </div>                </div>                <!-- /.row -->                <div class="row">                    <div class="col-lg-12">                        <div class="alert alert-info alert-dismissable">                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>                            <i class="fa fa-info-circle"></i>  Chào mừng các bạn đến với Themis web 2.1                        </div>                    </div>                </div>                <!-- /.row -->